MODCPCT-87 Rename module permissions
folio-org/mod-copycat pull request #112
Opened 2024-09-25 10:56 UTC by dmytrokrutii

2024-09-25 12:09 UTC, MikeTaylor requested changes
Please use "replaces" so that this is not a breaking change.

2024-10-03 13:15 UTC, dmytrokrutii commented
> Please use "replaces" so that this is not a breaking change.
@MikeTaylor New permissions in mod-source-record-storage and mod-source-record-manager already have the "replaces" keyword.
However, this does not negate the need to change the names in all the affected modules.

Taras Spashchenko:
>  And yes, if you change the permission name, you must change all references to the old name throughout the FOLIO in all repositories.

You also can see this https://github.com/folio-org/mod-data-import/pull/337#discussion_r1771429512

2024-10-09 10:29 UTC, KaterynaSenchenko commented on NEWS.md
> +* [MODCPCT-87](https://folio-org.atlassian.net/browse/MODCPCT-87) Update `source-manager-job-executions` to `3.4` and `source-storage-source-records `to `3.5`
Please move this enty under the unreleased version of the module

2024-10-10 10:46 UTC, KaterynaSenchenko approved these changes

2024-10-14 11:44 UTC, MikeTaylor commented
Yes, so long as the upstream module is using `replaces` correctly, we should be OK. Of course, this present PR must be merged _after_ that one — it doesn't need to be synchronized with it.

A more relaxed implementation path here would be to _now_ go ahead and merge a PR that only updates the dependency on the `source-manager-job-executions` interface, to _add_ version 3.4 to the existing 2.0 and 3.0, as the code can continue to consume the permissions by their own names (thanks to the use of `replaces`). You could then make a second PR some time later, at your leisure, that switches to using the new names.

But if you prefer to just go ahead and do this all at once, I won't place an impediment in your path.

2024-10-17 13:33 UTC, merged